spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:tcp://localhost/~/order-guppy; #DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 강의자료:  https://ancient-citron-06b.notion.site/1a78337d9ad241cf86a3ff676e2cf3b5