version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: board-jpa
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: board_jpa
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./data/:/var/lib/mysql
