version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'proddb'
      MYSQL_ROOT_HOST : '%'
      MYSQL_ROOT_PASSWORD: 'prodpassword'
    ports:
      - '3307:3306'
