spring:
  datasource:
    url: jdbc:h2:mem:board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
