spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_jpa
    username: root
    password : dudwl0804!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true