spring:
  datasource:
    url: jdbc:h2:mem:suhyun-board;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
