spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    #show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    generate-ddl: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:jpa


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE