spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-jpa-board;
    usernmae: sa
    password:

  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create