spring:
  profiles:
    active: local
    group:
      development:
        - dev
      production:
        - prod
      local:
        - local

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:local
    username: sa
    password:

logging:
  file:
    path: ./logs/local

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/springBoardJpaDev
    username: sa
    password:

logging:
  file:
    path: ./logs/dev

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/springBoardJpaDev
    username: sa
    password:

logging:
  file:
    path: ./logs/prod
