spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        query.in_clause_parameter_padding: true
        hbm2ddl:
          auto: create

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true