spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        query.in_clause_parameter_padding: true
