spring:
  profiles:
    active: board
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
