spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/post
    username: sa
    password:
  jpa:
    database: h2
    properties:
      hibernate:
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  profiles:
    active: local
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace