spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gesipan
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
