spring:
  datasource:
    url: jdbc:mariadb://localhost/spring_board
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true