spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  messages:
    basename: messages,errors
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
