spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_db
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: false
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
