version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: board
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: board
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
