spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/post
    username:
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
  server:
    servlet:
      encoding:
        charset: utf-8
        enabled: true
        force: true